### ISSUE TITLE
difficulty getting this to work with Rails 5.1.1

### ISSUE THREAD

**Issue by ericcf** [seattlerb/minitest-bisect#16]
I've read through the README and closed issues, but have been unable so far to get this working with a Rails 5.1.1 application.

Here's the command and output:

```bash
$ MTB_VERBOSE=2 minitest_bisect --seed=26867 -Itest $(find test/presenters -type f -name \*_test.rb)

/Users/ericcf/.rvm/rubies/ruby-2.3.4/bin/ruby -Itest -e 'require "./test/presenters/activity_list_presenter_test.rb" ; require "./test/presenters/has_translations_test.rb" ; require "./test/presenters/participant_presenter_test.rb" ; require "./test/presenters/progress_bar_presenter_test.rb"' -- --seed\=26867 --server 92520

reproducing.../Users/ericcf/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/test_unit/minitest_plugin.rb:62:in `plugin_rails_options': invalid option: --server (OptionParser::InvalidOption)
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:201:in `block (2 levels) in process_args'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:199:in `each'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:199:in `block in process_args'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:169:in `new'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:169:in `process_args'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:123:in `run'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/test_unit/minitest_plugin.rb:77:in `run'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun'
Coverage report generated for MiniTest to /Users/ericcf/work/qse/coverage. 39 / 2989 LOC (1.3%) covered.
 in 5.45 sec
Reproduction run passed? Aborting.
Try running with MTB_VERBOSE=2 to verify.
```

Can I provide any further information that would help diagnose this?

Thanks.

Edit: I've already added `minitest-bisect` to my development and test groups in my `Gemfile` and bundled.

**Comment by zenspider** [comment]
Try that last line in the output:

```
Try running with MTB_VERBOSE=2 to verify.
```

Also, remove simplecov from the equation.

**Comment by ericcf** [comment]
Hmm. I added `MTB_VERBOSE=2` in front of the command already. After removing simplecov here's the command:
```
MTB_VERBOSE=2 minitest_bisect --seed=26867 -Itest $(find test/presenters -type f -name \*_test.rb)
```
and here's the output:
```
/Users/ericcf/.rvm/rubies/ruby-2.3.4/bin/ruby -Itest -e 'require "./test/presenters/activity_list_presenter_test.rb" ; require "./test/presenters/has_translations_test.rb" ; require "./test/presenters/participant_presenter_test.rb" ; require "./test/presenters/progress_bar_presenter_test.rb"' -- --seed\=26867 --server 3698

reproducing.../Users/ericcf/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/test_unit/minitest_plugin.rb:62:in `plugin_rails_options': invalid option: --server (OptionParser::InvalidOption)
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:201:in `block (2 levels) in process_args'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:199:in `each'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:199:in `block in process_args'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:169:in `new'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:169:in `process_args'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:123:in `run'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/test_unit/minitest_plugin.rb:77:in `run'
	from /Users/ericcf/.rvm/gems/ruby-2.3.4/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun'
 in 6.52 sec
Reproduction run passed? Aborting.
Try running with MTB_VERBOSE=2 to verify.
```

Thanks for your help. I apologize if I'm missing something obvious!

**Comment by splattael** [comment]
Same here :disappointed: 

I suspect that the load order of MT extensions is important here.

Rails' MT plugin [evaluates the options](https://github.com/rails/rails/blob/990a4dbbca5b7a8cf3d01861cb66deae456d370e/railties/lib/rails/test_unit/minitest_plugin.rb#L62) and complains about missing `--server` option because the MT server plugin is not loaded yet.

The order of the extensions is in my case: `["rails", "server", "guard_minitest", "pride"]`

I don't know how to force Rails' MT plugin to be loaded at the very end. :man_shrugging:

**Comment by splattael** [comment]
I've just learned that Rails' MT plugin puts itself in front on purpose:
https://github.com/rails/rails/blob/990a4dbbca5b7a8cf3d01861cb66deae456d370e/railties/lib/rails/test_unit/minitest_plugin.rb#L145

And oh, there is already PR on Rails' repo to fix this: rails/rails#29572

**Comment by padi** [comment]
Having this issue as well with Rails 5.1. Installed the gem via Gemfile. @splattael how were you able to fix this without having to update Rails?

**Comment by splattael** [comment]
@padi Sadly, I wasn't :/ I had to use the branch from https://github.com/rails/rails/pull/29572

Now, it's fixed and it has even been backported to 5.0 :+1:

**Comment by splattael** [comment]
@ericcf Can you try [Rails 5.1.3](https://rubygems.org/gems/rails/versions/5.1.3) and give feedback?

Refs [CHANGELOG](https://github.com/rails/rails/blob/5-1-stable/railties/CHANGELOG.md#rails-513rc1-july-19-2017).

**Comment by ericcf** [comment]
@splattael upgrading to Rails 5.1.3, I'm not getting the same error any more. However I'm getting lots of test failures that I don't see when simply running the tests with `rails test ...`. I'll have to dig into these further, but as far as I'm concerned my original issue has been solved.

**Comment by zenspider** [comment]
Can you leave this open until any side issues are resolved and update this ticket?

**Comment by ericcf** [comment]
No problem.

**Comment by padi** [comment]
@splattael we've just upgraded our app to rails 5.1.3 and the error's gone, in particular:

`invalid option: --server (OptionParser::InvalidOption)`

**Comment by zenspider** [comment]
Sooo... should this be closed now? Should there be any doco changes?

**Comment by splattael** [comment]
@zenspider Upgrading to Rails 5.1.3 did fix the issue for me, @ericcf and @padi.

I don't see how we can improve the docs in this issue.

From my point of view: Close it :dancer:

**Comment by ericcf** [comment]
Agreed - it works nicely for me on Rails 5.1.4. Can be closed - thanks!

**Comment by iamarmanjon** [comment]
Wow timely issue! I just had this error, upgraded from 5.1.2 to 5.1.4 solves it too.

**Comment by zenspider** [comment]
Thanks everyone!
