### ISSUE TITLE
Bisect says run passed while it failed

### ISSUE THREAD

**Issue by cyrilchampier** [seattlerb/minitest-bisect#19]
After reading
https://github.com/seattlerb/minitest-bisect/issues/6
https://github.com/seattlerb/minitest-bisect/issues/7
https://github.com/seattlerb/minitest-bisect/issues/10

I still have the error.

Here is the command I launch and a (partial) output:

```
$ MTB_VERBOSE=2 bundle exec minitest_bisect --seed 41542 -Itest test/integration/configuration/organizations_test.rb test/controllers/concerns/domain_test.rb test/integration/doctor/mobile/login_test.rb

/Users/dcyril/.rbenv/versions/2.5.3/bin/ruby -Itest -e 'require "./test/integration/configuration/organizations_test.rb" ; require "./test/controllers/concerns/domain_test.rb" ; require "./test/integration/doctor/mobile/login_test.rb"' -- --seed 41542 --server 33658

reproducing...Started with run options --seed 41542 --server 33658

Integration::Doctor::Mobile::LoginTest::password forgotten
  test_resets_password_on_mobile_application                      PASS (16.75s)
Integration::Doctor::Mobile::LoginTest::password forgotten
  test_resets_password_on_web_application                         PASS (3.68s)
DomainTest
  test_should_#normalized_tld                                     PASS (0.85s)

[...]

Integration::Doctor::Mobile::LoginTest::pin authentication
  test_redirects_to_calendar_if_we_try_to_reconnect_or_login_while_already_connected ERROR (1.30s)
ActionController::RoutingError:         ActionController::RoutingError: No route matches [GET] "/sessions/new"

[...]

Integration::Doctor::Mobile::LoginTest
  test_should_notification_on_input_error                        ERROR (1.29s)
ActionController::RoutingError:         ActionController::RoutingError: No route matches [GET] "/sessions/new"

Finished in 63.21465s
30 tests, 253 assertions, 1 failures, 10 errors, 0 skips
 in 69.56 sec
Reproduction run passed? Aborting.
Try running with MTB_VERBOSE=2 to verify.
```

and just to be sure, bisect return 1:
```
$ echo $?
1
```

Am I missing something ?

Thanks

**Comment by zenspider** [comment]
```
Integration::Doctor::Mobile::LoginTest::password forgotten
  test_resets_password_on_mobile_application                      PASS (16.75s)
Integration::Doctor::Mobile::LoginTest::password forgotten
  test_resets_password_on_web_application                         PASS (3.68s)
DomainTest
  test_should_#normalized_tld                                     PASS (0.85s)
```

Hints that you're using some other set of reporters. Some of those gems are bad actors in the minitest world and are probably removing the remote reporter that is required to send results back to the server.

Please **remove** any and all custom reporting and try again. Remove. As in, they can't be in your Gemfile at all.

**Comment by cyrilchampier** [comment]
Thanks for your response.
Unfortunately, when I remove all reporters (we use https://github.com/kern/minitest-reporters), the tests are passing.
Probably because it modify the test order, but I have no easy way to verify it, since the default reporter only puts `.`.

Anyway, I successfully reproduced the correct sequence manually, I will try again next time I will track a flaky test.

**Comment by zenspider** [comment]
Can you explain that a bit more?

You're saying that when you run with minitest-reporters that `test_should_notification_on_input_error` has an error (`RoutingError`) but when you disable the minitest-reporters that you don't?

Reporters can't affect the outcome of a test, short of doing something on the side that initially changes the ordering of the test. I just checked out minitest-reporters and I don't see any calls to `srand` or `rand`... the `ansi` dependency does, so there might be some indirection that winds up in there...

Other than that, I can't come up with any other reason why/how a dependency would change the outcome of your tests.

If you run your tests with `-v` minitest will output the exact sequence of tests that are running. With some grepping and/or reformatting it should be diffable against a run with minitest-reporters on.

**Comment by zenspider** [comment]
Go one step further... monkeypatch `srand` and `rand` before minitest (or rails) loads to output `caller.first` so you can see where one sneaks in, if any. Something like:

```ruby
module Kernel
alias oldsrand srand
alias oldrand rand
def rand(*a)
  $stderr.puts "RAND CALLED: %s" % [caller.first]
  oldrand(*a)
end
...same
```

**Comment by cyrilchampier** [comment]
I start these tests with ruby, and `-v` add too much noise to be usable.

Correct me if I am wrong, but minitest does not guarantee the file order, when code changes, even when we fix the seed?
I think that's what happening here: the failure strongly depend on the interweaving of two files, and removing the gem and our specific reporter loader make minitest change this order.
