### ISSUE TITLE
Support minitest-server 1.0.6

### ISSUE THREAD

**Issue by N0xFF** [seattlerb/minitest-bisect#22]
With latest `minitest-server` 1.0.6 we got `NoMethodError` exception on test failure.

```
$ MTB_VERBOSE=2 bundle exec minitest_bisect --seed 61539 -Itest "test.rb"

/home/virtual/.rbenv/versions/2.6.3/bin/ruby -Itest:lib -Itest -e 'require "./test.rb"' -- --seed 61539 --server 11417

reproducing...Run options: --seed 61539 --server 11417

# Running:

.../home/virtual/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/minitest-server-1.0.6/lib/minitest/server_plugin.rb:56:in `block in sanitize': undefined method `error=' for #<Minitest::UnexpectedError: Unexpected exception> (NoMethodError)Did you mean?  error in 7.14 sec
Reproduction run passed? Aborting.
Try running with MTB_VERBOSE=2 to verify.
```

Looks like 1.0.6 version has incompatible changes.

**Comment by deivid-rodriguez** [comment]
Just run into the same thing. Downgrading to 1.0.5 works, so it should be easy to isolate.

**Comment by zenspider** [comment]
This should be fixed now by releasing a new version of minitest. Lemme know if that is not the case (I got bit my minitest-autorun and that should be totally related).

**Comment by zenspider** [comment]
Actually... you confirm and close please.

**Comment by AlexMooney** [comment]
Upgrading from minitest 5.13.0 to 5.14.0 fixed the problem for me.
